config/routes.rb
Rails.application.routes.draw do
  root "schedules#index"

  devise_for :users 

  resources :schedules

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user

  validates :date, presence: true
  validates :time, presence: true
  validates :total, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :schedules, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController
  before_action :authenticate_user!


  def index
    if user_signed_in?
      @schedules = current_user.schedules
  end

  def new
    @schedule = current_user.schedules.new
  end

  def create
    @schedule = current_user.schedules.new(schedule_params)
    if @schedule.save
      redirect_to @schedule
   else
      render :new, status: :unprocessable_entity
   end
    end
  end

  private
  def schedule_params
    params.require(:schedule).permit(:date, :time, :total)
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!

  def index
    if user_signed_in?
      @schedules = current_user.schedules
      # @schedules = Schedule.all
    end
  end

  def show
    @schedule = current_user.schedules.find(params[:id])
  end

  def new
    @schedule = current_user.schedules.new
  end

  def create
    @schedule = current_user.schedules.new(schedule_params)

    if @schedule.save
      redirect_to root_path
    else
        render :new, status: :unprocessable_entity
    end
  end

  def edit
    @schedule = current_user.schedules.find(params[:id])
  end

  def update
    @schedule = current_user.schedules.find(params[:id])

    if @schedule.update(schedule_params)
      redirect_to @schedule
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @schedule = current_user.schedules.find(params[:id])
    @schedule.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def schedule_params
    params.require(:schedule).permit(:date, :time, :total)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scheduler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <header>
        <%= link_to "Rails Blog", root_path %>
        <nav>
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Users", '#' %></li>
              <li>
                <a href="#">Account</a>
                <ul>
                  <li><%= link_to "Profile", '#' %></li>
                  <li><%= link_to "Settings", '#' %></li>
                  <li>
                    <%= link_to "Log out", destroy_user_session_path , method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", user_session_path %></li>
            <% end %>
          </ul>
        </nav>
      </header>
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message) %>
  <% end %>    
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/schedule/index.html.erb
<h1>Schedule#index</h1>
<p>Find me in app/views/schedule/index.html.erb</p>

<h1>Articles</h1>

<% if @schedules.empty? %>
    <%= "Please Add Schedules" %>
<% else %> <table>
        <% @schedules.each do |schedule| %>
            <tr>
                <td>
                    <a href="/schedules/<%= schedule.id %>">
                        <%= schedule.date %>
                    </a>
                </td>
                <td>
                        <%= schedule.time %>
                </td>

                <td>
                        <%= schedule.total %>
                </td>
            </tr>
        <% end %>
    <table>
<% end %>
    

app/views/schedules/_form.html.erb
<%= form_with model: @schedule do |form| %>
  <div>
    <%= form.label :date %><br>
    <%= form.date_field :date %>
    <% @schedule.errors.full_messages_for(:date).each do |message| %>
        <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :time %><br>
    <%= form.time_field :time %>
    <% @schedule.errors.full_messages_for(:time).each do |message| %>
        <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :total %><br>
    <%= form.number_field :total, in: 300..3000 %>
    <% @schedule.errors.full_messages_for(:total).each do |message| %>
        <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Edit Schedule</h1>

<%= render "form", schedule: @schedule %>

app/views/schedules/index.html.erb
<h1>Articles</h1>

<% if @schedules.empty? %>
    <%= "Please Add Schedules" %>
<% else %> <table>
        <% @schedules.each do |schedule| %>
            <tr>
                <td>
                    <a href="/schedules/<%= schedule.id %>">
                        <%= schedule.date %>
                    </a>
                </td>
                <td>
                    <%= schedule.time %>
                </td>

                <td>
                    <%= schedule.total %>
                </td>

                <td>
                    <%= link_to "check detailed", schedule %>
                </td>
            </tr>

        <% end %>
    <table>
<% end %>


<%= link_to "Add Schedule", new_schedule_path  %>
    

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= form_with model: @schedule do |form| %>
  <div>
    <%= form.label :date %><br>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :time %><br>
    <%= form.time_field :time %>
  </div>

  <div>
    <%= form.label :total %><br>
    <%= form.number_field :total, in: 300..3000 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/show.html.erb
<h1><%= "Detailed Schedule" %></h1>
 <p><%= "date: " + @schedule.date.to_s %></p>
<p><%= "time: " + @schedule.time.to_s %></p>
<p><%= "total: " + @schedule.total.to_s %></p> 

<%= link_to "edit schedule", edit_schedule_path %> |
<%= button_to "Destroy", schedule_path(@schedule), method: :delete %></li>